import "../style/style.css";
import Header from "../components/header";
import Footer from "../components/footer";

export const metadata = {
  title: "title 미정",
  description: "Generated by create jhs",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div id="wrap">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
